name: claro_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  json_annotation: ^4.9.0
  get_it: ^8.0.2


dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: any
  lints: ^5.0.0
  test: ^1.25.8
  mockito: ^5.3.2
